### ISSUE TITLE
Zig by example topic on `for.zig` on line 15 not working

### ISSUE THREAD

**Issue by reubendevries** [ibokuri/zigbyexample#4]
using the following version:

`zig 0.9.1`

get the following error when trying to zig format my `for.zig` file:

`for.zig|15 col 15| : error: expected ')', found ','  `

I even copied the code straight from the website, looks like zig won't allow both the `array` and the `&array` between the  `( )` or it doens't like the comma seperating the two (which is also found in your example.

When I try to compile I get pretty much the same error:

```shell
for.zig:15:15: error: expected ')', found ','
    for (array, &array) |val, *ref| {
```

**Comment by phan-do** [comment]
Hi Reuben, the multi-object for loop syntax was introduced in the `0.11` release of Zig (see [here](https://ziglang.org/download/0.11.0/release-notes.html#toc-Multi-Object-For-Loops) for more details), so you won't be able to compile the for loop example on version `0.9.1`.

Generally speaking, I want to have the site reflect the latest changes in Zig (at least, up until `1.0`), which is why the new syntax is showcased. Sorry for the confusion!

**Comment by reubendevries** [comment]
Thanks for the clarification!
